---
apiVersion: v1
kind: Secret
metadata:
  name: repo-sshkey
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: ssh://git@github.com/durga61/aws-cloud-infra.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACCu4BOhhVTjw0bdr+3a9QM6A9SQs+aFgX39maeXeyjMXAAAAKAu5jZ6LuY2
    egAAAAtzc2gtZWQyNTUxOQAAACCu4BOhhVTjw0bdr+3a9QM6A9SQs+aFgX39maeXeyjMXA
    AAAEAqKsxTEb1rRK+b4K7PaoIAGXK114127GPujGasFSR1la7gE6GFVOPDRt2v7dr1AzoD
    1JCz5oWBff2Zp5d7KMxcAAAAGHBkdXJnYXByYXNhZDYxQGdtYWlsLmNvbQECAwQF
    -----END OPENSSH PRIVATE KEY-----
  insecure: "false"
  enableLfs: "false"
