apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: pdurgaprasad61@gmail.com
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
    - dns01:
        route53:
          hostedZoneID: Z02682411LNVGL09UV93I
          region: ap-south-1
      selector:
        dnsZones:
        - "durgadevops.online"
    - http01:
        ingress:
          class: nginx
